listen: 0.0.0.0:8080
listen_pprof: 0.0.0.0:7008

target: http://127.0.0.1:9091/receive
log_level: debug
timeout: 10s
timeout_shutdown: 0s

tenant:
  label: tenant
  label_remove: true
  header: X-Scope-OrgID
  default: ""
