apiVersion: v1
kind: Service
metadata:
  name: cortex-tenant
  namespace: cortex
spec:
  ports:
    - name: cortex-tenant
      port: 8080
      protocol: TCP
      targetPort: cortex-tenant
  selector:
    release: cortex-tenant
